# HTTP_SERVER_ENABLED = True
import logging

SERVER_ADDRESS = 'localhost'
HTTP_PORT = 8000

UDP_PORT = 64327

# Selenium translator options
HEADLESS_MODE = False
MAX_WAIT_FOR_TRANSLATION = 60
SELENIUM_TIMEOUT = MAX_WAIT_FOR_TRANSLATION

SENTENCE_SEPARATOR = "\n-&----&-\n"
ID_SEPARATOR = "\n"
MIN_WAIT_FOR_TRANSLATION = 5
MAX_WAIT_FOR_TRANSLATION = 60
MAX_CHARACTERS_PER_BUFFER = 3200
MAX_NUMBER_OF_REQUESTS_WITH_SAME_DRIVER = 30
WAIT_BETWEEN_DRIVER_CHANGE = 120
MAX_TIMEOUTS_BEFORE_ASSUMING_TEMPORARY_BAN = 5
SELENIUM_TIMEOUT = 5
URL = "http://www.deepl.com"
MINIMUM_ACCEPTABLE_TRANSLATION_RATIO = 0.2
WAIT_FOR_IP_UNBLOCK = 60*60
TRANSLATION_DICTIONARY_FILENAME = 'translation_dictionary.pkl'
MAX_TRANSLATION_ITERATIONS = 3
LOGGING_LEVEL = logging.INFO
